[package]
name = "gw-metrics"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gw-core = { path = "../gw-core" }
anyhow.workspace = true
prometheus.workspace = true
axum.workspace = true
tokio.workspace = true
