# Prometheus configuration for Ghostwarden monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "ghostwarden_rules.yml"

scrape_configs:
  - job_name: 'ghostwarden'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"
